version: '3.8'
# To rebuild images when Dockerfile or source code changes, use:
# docker compose up --build
services:
  linear-regression-backend:
    # image: linear_regression_image:v3
    build: 
      context: backend/
    ports:
      - "8000:8000"
    container_name: linear_regression_backend
    restart: unless-stopped

  frontend:
    build:
      context: frontend/
    ports:
      - "8501:8501"
    container_name: streamlit_frontend
    depends_on:
      - linear-regression-backend

